backend:
  name: git-gateway
  branch: feature/test-with-new
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img

collections:
  - name: "service"
    label: "Service"
    folder: "src/pages/service-page"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "service-name"}
      - {label: "Service Name", name: "servicename", widget: "string"}
      - {label: "Service Description", name: "servicedescription", widget: "text"}

  - name: "services"
    label: "Services Page (Elaborate)"
    folder: "src/pages/services"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
    - {label: "Template Key", name: "templateKey", widget: "hidden", default: "service-post"}
    - {label: "Title", name: "title", widget: "string"}
    - {label: "Body", name: "body", widget: "markdown"}
    - {label: "Tags", name: "tags", widget: "list"}

  - name: "projects"
    label: "Projects Page (Elaborate)"
    folder: "src/pages/projects"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
    - {label: "Template Key", name: "templateKey", widget: "hidden", default: "project-post"}
    - {label: "Title", name: "title", widget: "string"}
    - {label: "Body", name: "body", widget: "markdown"}
    - {label: "Tags", name: "tags", widget: "list"}

  - name: "client"
    label: "Client"
    folder: "src/pages/client-page"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
    - {label: "Title", name: "title", widget: "string"}
    - {label: Image, name: image, widget: image}
    - {label: "Template Key", name: "templateKey", widget: "hidden", default: "client-name"}
    - {label: "Client Name", name: "clientname", widget: "string"}
    - {label: "Client Description", name: "clientdescription", widget: "text"}

  - name: "project"
    label: "Project"
    folder: "src/pages/project-page"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
    - {label: "Title", name: "title", widget: "string"}
    - {label: Image, name: image, widget: image}
    - {label: "Template Key", name: "templateKey", widget: "hidden", default: "project-name"}
    - {label: "Client Name", name: "projectname", widget: "string"}
    - {label: "Client Description", name: "projectdescription", widget: "text"}

  - name: "team"
    label: "Team Member"
    folder: "src/pages/team-page"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
    - {label: "Title", name: "title", widget: "string"}
    - {label: "Template Key", name: "templateKey", widget: "hidden", default: "team-name"}
    - {label: Image, name: image, widget: image}
    - {label: "Team Member Name", name: "membername", widget: "string"}
    - {label: "Team Member Title", name: "membertitle", widget: "text"}
    - {label: "Team Member Description", name: "memberdescription", widget: "text"}

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: Title, name: title, widget: string}
          - {label: Hero Image, name: image, widget: image}
          - {label: Hero Text, name: heading, widget: string}
          - {label: "Services Blurb", name: "serviceblurb", widget: string}
          - {label: "Client Blurb", name: "clientblurb", widget: string}
          - {label: "Project Blurb", name: "projectblurb", widget: string}
          - {label: "Team Blurb", name: "teamblurb", widget: string}
          - {label: "Contact Blurb", name: "contactblurb", widget: string}
          - {label: "Contact Heading", name: "contactheading", widget: string}
          - {label: "Contact Sub Heading", name: "contactsubheading", widget: string}
          - {label: "Contact Email", name: "contactemail", widget: string}
          - {label: "Contact Phone", name: "contactphone", widget: string}
          - {label: "Contact Address First Line", name: "contactaddresslineone", widget: string}
          - {label: "Contact Address Second Line", name: "contactaddresslinetwo", widget: string}